### ISSUE TITLE
Add multiple memes ability

### ISSUE THREAD

**Issue by innacc** [epodol/bearbot#2]
Basically automeme. It would be the meme command with a loop basically

**Comment by epodol** [comment]
This is a great idea! I would recommend the following implementation:
Add an optional option to the meme command named `count` (default 1) which loops over the fetch code.
Possible issues:
- Meme API may return the same meme multiple times when called sequentially
- Embeds per message limits

Let me know if you would like to implement this. Thanks for the issue!

**Comment by epodol** [comment]
This has been added in version v0.3.0!
